<?php
header('Content-Type: application/json; charset=utf-8');
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Headers: Content-Type');
$config=require __DIR__.'/config.php';
try{$pdo=new PDO($config['dsn'],$config['user'],$config['pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);}catch(Throwable $e){http_response_code(500);echo json_encode(['success'=>false,'message'=>'Database connection failed']);exit;}
function body(){return json_decode(file_get_contents('php://input'),true)?:[];} function out($x){echo json_encode(['success'=>true]+$x);exit;} function fail($m,$c=400){http_response_code($c);echo json_encode(['success'=>false,'message'=>$m]);exit;}
$action=$_GET['action']??'';$d=body();session_start();
if($action==='login'){ $s=$pdo->prepare("SELECT id,name,email,password_hash,role FROM users WHERE email=? AND active=1 LIMIT 1");$s->execute([$d['email']??'']);$u=$s->fetch();if(!$u||!password_verify($d['password']??'',$u['password_hash']))fail('Invalid email or password',401);unset($u['password_hash']);$_SESSION['user']=$u;out(['user'=>$u]);}
$user=['id'=>null,'name'=>'Local Admin','email'=>'','role'=>'ADMIN'];
if($action==='create_payment'){if(!$d['payment_date']||!$d['agent_name'])fail('Date and agent are required');$usdt=(float)($d['usdt']??0);$div=(float)($d['divided_by']??0);$inr=round($usdt*$div,2);$s=$pdo->prepare("INSERT INTO payments(payment_date,agent_name,ecode,ops_manager,tl,atl_name,payment_mode,usdt,divided_by,inr_amount,received_in,cash_received,remarks,created_by) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?,?)");$s->execute([$d['payment_date'],$d['agent_name'],$d['ecode']??null,$d['ops_manager']??null,$d['tl']??null,$d['atl_name']??null,$d['payment_mode']??'P2P',$usdt,$div,$inr,$d['received_in']??null,$d['cash_received']??0,$d['remarks']??null,$user['id']]);out(['id'=>$pdo->lastInsertId()]);}
function dates($d){$w=[];$p=[];if(!empty($d['from'])){$w[]='payment_date>=?';$p[]=$d['from'];}if(!empty($d['to'])){$w[]='payment_date<=?';$p[]=$d['to'];}return [$w,$p];}
if($action==='dashboard'){[$w,$p]=dates($d);$where=$w?'WHERE '.implode(' AND ',$w):'';$q=$pdo->prepare("SELECT COUNT(*) transactions,COALESCE(SUM(usdt),0) usdt,COALESCE(SUM(inr_amount),0) inr,COALESCE(SUM(cash_received),0) cash FROM payments $where");$q->execute($p);$k=$q->fetch();$q=$pdo->prepare("SELECT payment_date date,SUM(inr_amount) inr FROM payments $where GROUP BY payment_date ORDER BY payment_date");$q->execute($p);$daily=$q->fetchAll();$q=$pdo->prepare("SELECT COALESCE(ops_manager,'Unassigned') name,SUM(inr_amount) inr FROM payments $where GROUP BY ops_manager ORDER BY inr DESC");$q->execute($p);$ops=$q->fetchAll();$q=$pdo->prepare("SELECT payment_mode mode,SUM(inr_amount) inr FROM payments $where GROUP BY payment_mode ORDER BY inr DESC");$q->execute($p);$modes=$q->fetchAll();out(compact('k','daily','ops','modes'));}
if($action==='reports'){[$w,$p]=dates($d);if(!empty($d['ops'])){$w[]='ops_manager LIKE ?';$p[]='%'.$d['ops'].'%';}if(!empty($d['mode'])){$w[]='payment_mode=?';$p[]=$d['mode'];}$where=$w?'WHERE '.implode(' AND ',$w):'';$q=$pdo->prepare("SELECT * FROM payments $where ORDER BY payment_date DESC,id DESC");$q->execute($p);out(['rows'=>$q->fetchAll()]);}
if($action==='admin'){if($user['role']!=='ADMIN')fail('Admin access required',403);$users=$pdo->query("SELECT id,name,email,role,active,created_at FROM users ORDER BY id DESC")->fetchAll();$stats=['users'=>count($users),'payments'=>(int)$pdo->query("SELECT COUNT(*) FROM payments")->fetchColumn()];out(compact('users','stats'));}
if($action==='create_user'){if($user['role']!=='ADMIN')fail('Admin access required',403);$hash=password_hash($d['password'],PASSWORD_DEFAULT);$s=$pdo->prepare("INSERT INTO users(name,email,password_hash,role) VALUES(?,?,?,?)");$s->execute([$d['name'],$d['email'],$hash,$d['role']]);out(['id'=>$pdo->lastInsertId()]);} fail('Unknown action');
?>